services:
  - type: web
    name: dunong-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVarGroups: []
    autoDeploy: true
